version: '3'

services:
  nestjs-example-app:
    build: .
    container_name: nestjs-example-app
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - nestjs-example-db

  nestjs-example-db:
    build: .docker/postgres
    container_name: nestjs-example-db
    restart: on-failure
    tty: true
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
